movie_review/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("reviews.urls")),
    path('accounts/', include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.main, name="main"),
    path("reviews/index/", views.index, name="index"),
    path("reviews/create/", views.create, name="create"),
    path("reviews/<int:review_pk>/", views.detail, name="detail"),
    path("reviews/<int:review_pk>/update", views.update, name="update"),
    path("reviews/<int:review_pk>/delete", views.delete, name="delete"),
    path("reviews/<int:review_pk>/likes", views.likes, name="likes"),
    path("reviews/<int:review_pk>/comments", views.comments, name="comments"),
    path(
        "reviews/<int:review_pk>/comments/<int:comment_pk>/delete/",
        views.comments_delete,
        name="comment_delete",
    ),
    path("reviews/search/", views.search, name="search"),
]

reviews/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.conf import settings

# Create your models here.
class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    subtitle = models.CharField(max_length=40)
    like_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_user"
    )
    
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.CharField(max_length=60)

reviews/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            "title",
            "subtitle",
            "content",
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
        ]

reviews/views.py
from django.shortcuts import redirect, render, get_object_or_404
from reviews.forms import ReviewForm, CommentForm
from .models import Review, Comment
from django.http import HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from django.db.models import Q

# Create your views here.
def main(request):
    return render(request, "reviews/main.html")


def index(request):
    review = Review.objects.all()
    context = {"review": review}
    return render(request, "reviews/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        forms = ReviewForm(request.POST)
        if forms.is_valid():
            review = forms.save(commit=False)
            review.user = request.user
            review.save()
            return redirect("reviews:index")

    else:
        forms = ReviewForm()
    context = {
        "forms": forms,
    }
    return render(request, "reviews/create.html", context)


def detail(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    forms = CommentForm()
    context = {
        "review": review,
        "forms": forms,
    }
    return render(request, "reviews/detail.html", context)


@login_required
def update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.method == "POST":
        forms = ReviewForm(request.POST, instance=review)
        if forms.is_valid():
            forms.save()
            return redirect("reviews:detail", review_pk)

    else:
        forms = ReviewForm(instance=review)
    context = {
        "forms": forms,
    }
    return render(request, "reviews/update.html", context)


@login_required
def delete(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    review.delete()
    return redirect("reviews:index")


def likes(request, review_pk):
    if request.user.is_authenticated:
        review = Review.objects.get(pk=review_pk)

        if review.like_user.filter().exists():
            review.like_user.remove(request.user)
        else:
            review.like_user.add(request.user)
        return redirect("reviews:detail", review_pk)
    else:
        return HttpResponseForbidden()


def search(request):
    if request.method == "GET":
        content_list = Review.objects.all()
        search = request.GET.get("search", "")

        if search:
            search_list = content_list.filter(
                Q(title__icontains=search)
                | Q(content__icontains=search)
                | Q(subtitle__icontains=search)
            )
            return render(request, "reviews/search.html", {"search": search_list})


@login_required
def comments(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.method == "POST":
        if request.user.is_authenticated:
            forms = CommentForm(request.POST)
            if forms.is_valid():
                comment = forms.save(commit=False)
                comment.review = review
                comment.user = request.user
                comment.save()
                return redirect("reviews:detail", review_pk)


@login_required
def comments_delete(request, review_pk, comment_pk):
    if request.method == "POST":
        # 댓글 작성자만 삭제 가능
        review = get_object_or_404(Review, pk=review_pk)
        comment = review.comment_set.all().get(pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    # GET으로 요청했을 경우 반응 없게
    return redirect("reviews:detail", review_pk)

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form forms %}
  <input type="submit" class="btn btn-outline-primary" value="작성">
</form>
{% endblock content %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <!--게시글-->
  <div class="p-4">
    <div class="row justify-content-center">
      <div class="col-md-12 col-lg-6">

        <!--게시글-->
        <div class="bg-gray-100 p-3 mb-4" style="border-radius: 1rem; box-shadow: 2px 3px 7px rgba(0, 0, 0, 0.493);">
          <p class="text-end" style="font-size: 1rem;">작성자
            {{ review.user }}</p>
          <p class="fw-light mb-1 text-end" style="font-size: 0.7rem;">
            {{ review.created_at }}
          </p>
          <h3>
            {{ review.title }}
          </h3>
          <p class="fst-italic">{{ review.subtitle }}</p>
          <hr>
          <p>{{ review.content }}</p>
          {% comment %} <a class="btn btn-primary" href="{% url 'reviews:likes' review.pk %}">쪼아요</a> {% endcomment %}
          <p>{{ review.like_user.count }}명이 좋아합니다.</p>
          <form action="{% url 'reviews:likes' review.pk %}" method='POST'>

            {% csrf_token %}
            {% if request.user in review.like_user.all %}
            <button class="btn btn-link text-danger">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart-fill" viewbox="0 0 16 16">
                <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
              </svg>
            </button>
            {% else %}
            <button class="btn btn-link text-danger">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart" viewbox="0 0 16 16">
                <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
              </svg>
            </button>
            {% endif %}
          </form>
            <div class="text-end">
              <a href="{% url 'reviews:update' review.pk %}" class="link-secondary">수정</a>
              <a href="{% url 'reviews:delete' review.pk %}" class="link-danger">삭제</a>
            </div>
          </div>
          <!-- 댓글 -->
          <div class="bg-gray-100 p-3 mb-4" style="border-radius: 1rem; box-shadow: 2px 3px 7px rgba(0, 0, 0, 0.493);">
          {% for comment in review.comment_set.all %}
            <!-- 댓글 작성자만 삭제버튼 보이게하기 -->
            <div class="d-flex justify-content-between px-3">
              <p>
                {{ comment.user }}| {{ comment.content }}
              </p>
              {% if request.user == comment.user %}
                <span>
                  <form action="{% url 'reviews:comment_delete' review.pk comment.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="삭제" class="btn btn-sm btn-outline-danger">
                  </form>
                </span>
              {% endif %}
            </div>
          {% endfor %}
          <!-- 댓글 작성폼 -->
          <form action="{% url 'reviews:comments' review.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form forms %}
            <div class="d-flex justify-content-end">
              <input class="btn btn-sm btn-warning" type="submit" value="작성"></div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block active %}
  <li class="nav-item">
    <a class="nav-link navi navi-active" aria-current="page" href="{% url 'reviews:index' %}">HOME</a>
  </li>
  <li class="nav-item">
    <a class="nav-link navi" href="{% url 'reviews:create' %}">NEW REVIEW</a>
  </li>
{% endblock active %}
{% block content %}
  <h1 class="m-3 fw-bold">Review</h1>
  <hr>
  <!-- 카드 -->
  <div class="card m-3 container mx-auto border-0">
    {% for rev in review %}
    <div class="row g-0">
      <div class="col-md-4 d-flex justify-content-center p-5">
        {% if rev.image %}
        <img src="{{ review.image.url }}" class="img-fluid rounded-start" alt="...">
        {% else %}
        <img src="https://dummyimage.com/200/dedbdc/8084c2" alt="">
        {% endif %}
      </div>
        <div class="col-md-8">
          <div class="card-body p-5">
            <div class="d-flex">
              <p class="fw-bold text-muted fs-5">{{ rev.user }} | </p>
              <p class="fw-bold text-muted ms-2 fs-5">{{ rev.created_at }}</p>
            </div>
            <a href="{% url 'reviews:detail' rev.pk %}" class="text-decoration-none">
              <h3 class="card-title fw-bold text-decoration-none text-black">
                {{ rev.title }}
              </h3>
            </a>
            <p class="card-text fs-4">{{ rev.subtitle }}</p>
            <p class="card-text">
              <small class="text-muted">{{ rev.created_at}}</small>
            </p>
          </div>
        </div>
        <hr>
        {% endfor %}
      </div>
  </div>

{% endblock content %}

reviews/templates/reviews/main.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/aos@2.3.1/dist/aos.css"/>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/mainstyle.css' %}">
  </head>

  <body>
    <!-- Ref https://www.reddit.com/r/javascript/comments/dolagh/apple_airpods_pro_page_uses_a_lot_of_images_so_i/ -->
    <section>
      <video id="video" playsinline="playsinline" poster="https://assets.nflxext.com/ffe/siteui/vlv3/9737377e-a430-4d13-ad6c-874c54837c49/945eec79-6856-4d95-b4c6-83ff5292f33d/KR-ko-20220111-popsignuptwoweeks-perspective_alpha_website_large.jpg">
        <source src="https://assets.nflxext.com/ffe/siteui/vlv3/9737377e-a430-4d13-ad6c-874c54837c49/945eec79-6856-4d95-b4c6-83ff5292f33d/KR-ko-20220111-popsignuptwoweeks-perspective_alpha_website_large.jpg" type="jpg">
        Your browser does not support the video tag.
      </video>
      <div class="scroll-dummy">
        <h1>영화 리뷰 보고싶나여?</h1>
        <a href="{% url 'reviews:index' %}">리뷰 보기</a>
        <p>
          우리는 예지, 정아, 유영을 가졌습니다 👍
        </p>
      </div>
    </section>

    <script>
      var FRAMES = 148;
      var FPS = 30;
      var video = document.getElementById('video');

      window.addEventListener('scroll', function (e) {
        var time = (window.scrollY / 1000) * FRAMES / FPS;
        video.currentTime = time;
        console.log(time);
        // alert('Hizo scroll')
      });

      window.addEventListener('load', function (e) {
        video.pause();
        video.currentTime = 0;
      });
    </script>
  </body>

</html>

reviews/templates/reviews/search.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1 class="m-3">Review</h1>
  <div class="card m-3" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="..." class="img-fluid rounded-start" alt="...">
      </div>
      {% for rev in search %}
        <div class="col-md-8">
          <div class="card-body">
            <a href="{% url 'reviews:detail' rev.pk %}" class="text-decoration-none">
              <h5 class="card-title">
                {{ rev.title }}
              </h5>
            </a>
            <p class="card-text">{{ rev.subtitle }}</p>
            <p class="card-text">
              <small class="text-muted">{{ rev.created_at}}</small>
            </p>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>

{% endblock content %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form forms %}
    <input type="submit" class="btn btn-outline-primary" value="작성">
  </form>
{% endblock content %}