accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("", views.index, name="index"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
    path("<int:user_pk>/", views.detail, name="detail"),
]

movie_review/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("reviews.urls")),
    path('accounts/', include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.main, name="main"),
    path("reviews/index/", views.index, name="index"),
    path("reviews/create/", views.create, name="create"),
    path("reviews/<int:review_pk>/", views.detail, name="detail"),
    path("reviews/<int:review_pk>/update", views.update, name="update"),
    path("reviews/<int:review_pk>/delete", views.delete, name="delete"),
    path("reviews/<int:review_pk>/likes", views.likes, name="likes"),
    path("reviews/<int:review_pk>/comments", views.comments, name="comments"),
    path(
        "reviews/<int:review_pk>/comments/<int:comment_pk>/delete/",
        views.comments_delete,
        name="comment_delete",
    ),
    path("reviews/search/", views.search, name="search"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )
    image = ProcessedImageField(upload_to='images/', blank=True,
                                processors=[Thumbnail(60, 60)],
                                format='JPEG',
                                options={'quality':90})

    @property
    def full_name(self):
        return f"{self.last_name}{self.first_name}"

accounts/forms.py
from dataclasses import fields
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class SignupForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "image",)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SignupForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.http import HttpResponseForbidden
from django.contrib.auth.decorators import login_required

# Create your views here.
def signup(request):
    if request.method == "POST":
        forms = SignupForm(request.POST, request.FILES)
        if forms.is_valid():
            user = forms.save()
            auth_login(request, user)
            return redirect("reviews:index")
    else:
        forms = SignupForm()
    context = {
        "forms": forms,
    }
    return render(request, "accounts/signup.html", context)


def index(request):
    members = get_user_model().objects.all()
    return render(request, "accounts/index.html")


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("reviews:index")
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    messages.warning(request, "로그아웃 되었습니다")
    return redirect("reviews:index")


@login_required
def follow(request, user_pk):
    person = get_user_model().objects.get(pk=user_pk)
    if person != request.user:
        if person.followers.filter(pk=request.user.pk).exists():
            person.followers.remove(request.user)
        else:
            person.followers.add(request.user)
        return redirect("accounts:detail", user_pk)
    else:
        return HttpResponseForbidden()


def detail(request, user_pk):
    person = get_user_model()
    person = get_object_or_404(person, pk=user_pk)
    context = {
        "person": person,
    }
    return render(request, "accounts/detail.html", context)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4 p-3">
            {% if person.image %}
            <img src="{{ person.image.url }}" alt="">
            {% else %}
            <img src="https://dummyimage.com/400/ccb3cc/fff" alt="프사대체이미지">
            {% endif %}
        </div>
        <div class="col p-3">
            <div class="d-flex">
                <h2 class="fw-bold">{{ person }}<span class="fs-5 ms-3 fw-light">팔로잉 : {{ person.followings.count }} | </span><span class="fs-5 fw-light">팔로워 : {{ person.followers.count }}</span></h2>
                {% if request.user.is_authenticated %}
                <p class="ms-5">
                    <form action="{% url 'accounts:follow' person.pk %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" value="팔로우" class="btn btn-outline-primary">
                    </form>
                </p>
                {% endif %}
            </div>
            <p>이메일 : {{ person.email }}</p>
            <p>가입일 : {{ person.date_joined }}</p>
            <p>마지막 로그인 : {{ person.last_login }}</p>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

  <h3 class="m-3 text-center">회원 목록</h3>
  <hr>
  <div class="container m-5">
    {% if request.user.is_authenticated %}
      <table class="table">
        <thead>
          <th>ID</th>
          <th>이름</th>
          <th>follower</th>
          <th>following</th>
          <th>email</th>

        </thead>
        <tbody>
          {% for user in members %}
            <tr>
              <td>{{ user.id }}</td>
              <td>
                <a href="{% url 'accounts:detail' user.pk %}">{{ user }}</a>
              </td>
              <td>following:
                {{ user.followings.all|length}}

              </td>
              <td>
                follower:
                {{ user.followings.all|length}}
              </td>
              <td>
                {{ user.email }}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endif %}
  </div>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-outline-primary" value="로그인">
  </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form forms %}
    <input type="submit" class="btn btn-outline-primary" value="회원가입">
  </form>
{% endblock content %}